name: Java CICD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  java:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build the project
        run: mvn clean package

      - name: Changing the directory
        run: cd target

      - name: Run ColorFul App
        run: java -jar /home/adminuser/actions-runner/_work/javaapp_mvn/javaapp_mvn/target/colorful-app-1.0.0.jar

      - name: Checking the status of website in local
        run: curl http://localhost:8080

